### ISSUE TITLE
It doesn't indent the swich?

### ISSUE THREAD

**Issue by dhilst** [sapphirecat/php-psr2-vim#1]
I have this

```php
            switch ($type) {
            case 'bool':
                break;
            default:
            }
```
I expect it to indent the case lines right when I select the code and pres  `=` but it doesn't. Am I doing something wrong?

**Comment by sapphirecat** [comment]
No, you're not doing anything wrong. The plugin is really small and simple. It only alters the vim settings listed in the README.

I was using this in conjunction with [StanAngeloff/php.vim](https://github.com/StanAngeloff/php.vim) which, as far as I remember, does its own indenting.

**Comment by dhilst** [comment]
I achieved this by 

```
au FileType php set cinoptions=l1
```

Regards
